server:
    port: 15001
spring:
    data:
        mongodb:
            authentication-database: admin
            database: ecom_mongo
            host: 15.207.12.222
            password: word_pass
            port: 27017
            username: dbuser
divatt: 
  search:
    allowedFields: status
    longTypes: versionNumber
