server:
    port: 15001
    
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      format_sql: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://13.233.19.234:3306/divatt
    username: db_user
    password: P@sw0rd123
  data:
    mongodb:
      authentication-database: admin
      database: ecom_mongo
      host: 65.1.190.195
      password: word_pass
      port: 27017
      username: dbuser 

  application:
       name: ecomOauth
divatt: 
  search:
    allowedFields: status
    longTypes: versionNumber
   
    
          
logging:
  level:
    org.springframework.security: DEBUG       